# Generated by Django 3.0.9 on 2020-08-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('partid', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('partname', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Task Type',
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joinDate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='primeTask',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subTask',
        ),
        migrations.AddField(
            model_name='task',
            name='taskid',
            field=models.CharField(default=1, max_length=120, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='taskname',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='task',
            field=models.ManyToManyField(blank=True, related_name='task', to='users.Task'),
        ),
        migrations.AlterField(
            model_name='user',
            name='serve',
            field=models.CharField(blank=True, choices=[('재직', '재직'), ('휴직', '휴직'), ('퇴직', '퇴직')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('사원', '사원'), ('대리', '대리'), ('과장', '과장'), ('차장', '차장'), ('부장', '부장')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Serve',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.AlterField(
            model_name='user',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part', to='users.Part'),
        ),
    ]
