# Generated by Django 3.0.9 on 2020-08-04 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200804_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'Part Type'},
        ),
        migrations.AddField(
            model_name='task',
            name='assignpart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignpart', to='users.Part'),
        ),
    ]
