# Generated by Django 3.0.9 on 2020-08-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20200804_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('boardid', models.AutoField(primary_key=True, serialize=False)),
                ('boardname', models.CharField(max_length=150)),
                ('leaderauth', models.BooleanField(default=False)),
                ('boardauth', models.ManyToManyField(blank=True, related_name='boardauth', to='users.Part')),
            ],
            options={
                'verbose_name': 'Board Type',
            },
        ),
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('itemtitle', models.CharField(max_length=150)),
                ('itemcontent', models.TextField()),
                ('assginboardid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assginboardid', to='boards.Board')),
            ],
            options={
                'verbose_name': 'Board Item',
            },
        ),
    ]
