# Generated by Django 3.0.9 on 2020-08-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200804_1739'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='boardauth',
        ),
        migrations.AddField(
            model_name='board',
            name='assginpart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assginpart', to='users.Part'),
        ),
        migrations.AddField(
            model_name='board',
            name='assigntask',
            field=models.ManyToManyField(blank=True, related_name='assigntask', to='users.Task'),
        ),
    ]
