# Generated by Django 2.2.5 on 2020-08-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200804_1739'),
        ('boards', '0002_auto_20200804_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='assginpart',
        ),
        migrations.RemoveField(
            model_name='board',
            name='assigntask',
        ),
        migrations.AddField(
            model_name='board',
            name='categoryid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='classification',
            field=models.CharField(blank=True, choices=[('카테고리', '카테고리'), ('아이템', '아이템')], max_length=10),
        ),
        migrations.AddField(
            model_name='board',
            name='itemid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='qualityauth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='writeauth',
            field=models.ManyToManyField(blank=True, related_name='writeauth', to='users.Part'),
        ),
    ]
