# Generated by Django 2.2.5 on 2020-08-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200807_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='detailid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
