# Generated by Django 2.2.5 on 2020-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_board_detailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='classification',
            field=models.CharField(blank=True, choices=[('카테고리', '카테고리'), ('중분류', '중분류'), ('소분류', '소분류')], max_length=10),
        ),
    ]
